/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "us-west-2",
  aws_appsync_graphqlEndpoint:
    "https://u6py6nyoorhafiy7a5o4jqnd7q.appsync-api.us-west-2.amazonaws.com/graphql",
  aws_appsync_region: "us-west-2",
  aws_appsync_authenticationType: "API_KEY",
  aws_appsync_apiKey: "da2-vnalyuriqfhkvpte26repcorzi",
  aws_cognito_identity_pool_id:
    "us-west-2:f17fbb69-84be-4096-af62-55ef92ec58b5",
  aws_cognito_region: "us-west-2",
  aws_user_pools_id: "us-west-2_laq5Cv3zu",
  aws_user_pools_web_client_id: "kmo87la9ost7bbr7jqp76s63n",
  oauth: {},
  aws_cognito_username_attributes: ["EMAIL"],
  aws_cognito_social_providers: [],
  aws_cognito_signup_attributes: ["EMAIL"],
  aws_cognito_mfa_configuration: "OPTIONAL",
  aws_cognito_mfa_types: ["TOTP"],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 12,
    passwordPolicyCharacters: [
      "REQUIRES_LOWERCASE",
      "REQUIRES_NUMBERS",
      "REQUIRES_SYMBOLS",
      "REQUIRES_UPPERCASE"
    ]
  },
  aws_cognito_verification_mechanisms: ["EMAIL"]
}

export default awsmobile
