name: Build test branch

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install
        run: yarn install

      - name: Install Amplify CLI
        run: curl -sL https://aws-amplify.github.io/amplify-cli/install | bash && $SHELL

      - name: Pull Amplify project
        run: amplify pull --appId d21bdgrb1tdkdd --envName test

      - name: Add graphql capabilities
        run: amplify update api

      - name: Build
        run: yarn build build --if-present
